### ISSUE TITLE
Crashing when trying to watch certain streams

### ISSUE THREAD

**Issue by memesalot** [xiaodoudou/PlexIPTV#19]
```
events.js:183

      throw er; // Unhandled 'error' event

      ^
Error: connect ECONNREFUSED 185.246.209.106:80
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! plexiptv@1.0.4 start:docker: `node index.js -s `pwd`/config/settings.json`
npm ERR! Exit status 1

npm ERR! Failed at the plexiptv@1.0.4 start:docker script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:

npm ERR!     /root/.npm/_logs/2018-06-24T08_17_49_132Z-debug.log```



I get this crash message when I try to open up some streams, some work and some do this.

**Comment by xiaodoudou** [comment]
Fixed in [1.1.0](https://github.com/xiaodoudou/PlexIPTV/releases/tag/1.1.0), sorry it took so long.

That `ECONNREFUSED` was an unhandled error event, which is why the whole thing died instead of just that channel failing. One dead stream took the server down for everything.

Errors are caught properly now. A stream that won't connect gets retried a few times, then gives up and returns a 502 while everything else keeps running. If the provider is actively refusing you (403, or the Xtream `458 connection limit reached`) it doesn't retry at all, because reconnecting won't help. With 458 it can actively hurt: hammering a line that's already at its connection limit can knock out the streams you've got working, depending on how your provider handles it.
