### ISSUE TITLE
[Synology NAS] PlexIPTV Error: Invalid protocol

### ISSUE THREAD

**Issue by ThomasDalla** [xiaodoudou/PlexIPTV#32]
Setup:
* xiaodoudoufr-plexiptv docker on Synology NAS 916+
* plex on the same NAS
* m3u from my ISP (Free, http://mafreebox.freebox.fr/freeboxtv/playlist.m3u)
* epg from http://xmltvfree.free.fr/

Setup seems OK, I can see the channels in Plex:<br>
![image](https://user-images.githubusercontent.com/609945/68541803-d5342500-039b-11ea-8618-7f85be56848d.png)

But when I try to watch one of them, I get an error message.

Logs:

```
date | stream | content
-- | -- | --
2019-11-10 09:02:09 | stdout | [33;1mplexiptv:dvr:verbose [0m2019/11/10 09:02:09.9500 🔭 [32mdiscover[39m Received a discover request. [33m+1m[0m
2019-11-10 09:02:09 | stdout | [33;1mplexiptv:dvr:verbose [0m2019/11/10 09:02:09.9520 🔭 [32mlineup[39m Received a lineup request. [33m+2ms[0m
2019-11-10 09:02:09 | stdout | [33;1mplexiptv:dvr:verbose [0m2019/11/10 09:02:09.9530 🔭 [32mchannels[39m Return 679 channels. [33m+1ms[0m
2019-11-10 09:02:09 | stdout | [33;1mplexiptv:dvr:verbose [0m2019/11/10 09:02:09.9600 🔭 [32mlineupStatus[39m Received a lineup status request. [33m+7ms[0m
2019-11-10 09:02:09 | stdout | [33;1mplexiptv:index:verbose [0m2019/11/10 09:02:09.9930 🔭 [32mproxy[39m Receive a proxy for: 80019 [33m+2m[0m
2019-11-10 09:02:09 | stdout | [33;1mplexiptv:worker:verbose [0m2019/11/10 09:02:09.9940 🔭 [32mrequestFactory[39m Preloading: http://localhost:1245/channel/80019 (rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=497) [33m+1m[0m
2019-11-10 09:02:09 | stdout | [36;1mplexiptv:worker:warn [0m2019/11/10 09:02:09.9950 ⚠️ [32mrequest[39m Remote stream replied: Unknown Error (Unknown) [36m+2m[0m
2019-11-10 09:02:09 | stdout | [33;1mplexiptv:worker:error [0m2019/11/10 09:02:09.9950 🔥 [32mrequest[39m Error occured:
2019-11-10 09:02:09 | stdout | [33;1mplexiptv:worker:error [0m[ Error: Invalid protocol
2019-11-10 09:02:09 | stdout | [33;1mplexiptv:worker:error [0m    at Request.init (/opt/PlexIPTV/node_modules/request/request.js:338:51)
2019-11-10 09:02:09 | stdout | [33;1mplexiptv:worker:error [0m    at new Request (/opt/PlexIPTV/node_modules/request/request.js:105:8)
2019-11-10 09:02:09 | stdout | [33;1mplexiptv:worker:error [0m    at request (/opt/PlexIPTV/node_modules/request/index.js:53:11)
2019-11-10 09:02:10 | stdout | [33;1mplexiptv:worker:error [0m    at Worker.requestFactory (/opt/PlexIPTV/worker.js:60:21)
2019-11-10 09:02:10 | stdout | [33;1mplexiptv:worker:error [0m    at new Worker (/opt/PlexIPTV/worker.js:26:25)
2019-11-10 09:02:10 | stdout | [33;1mplexiptv:worker:error [0m    at Preloader.preload (/opt/PlexIPTV/preloader.js:24:16)
2019-11-10 09:02:10 | stdout | [33;1mplexiptv:worker:error [0m    at Server.proxy (/opt/PlexIPTV/index.js:165:35)
2019-11-10 09:02:10 | stdout | [33;1mplexiptv:worker:error [0m    at Layer.handle [as handle_request] (/opt/PlexIPTV/node_modules/express/lib/router/layer.js:95:5)
2019-11-10 09:02:10 | stdout | [33;1mplexiptv:worker:error [0m    at trim_prefix (/opt/PlexIPTV/node_modules/express/lib/router/index.js:317:13)
2019-11-10 09:02:10 | stdout | [33;1mplexiptv:worker:error [0m    at /opt/PlexIPTV/node_modules/express/lib/router/index.js:284:7
2019-11-10 09:02:10 | stdout | [33;1mplexiptv:worker:error [0m    at param (/opt/PlexIPTV/node_modules/express/lib/router/index.js:354:14)
2019-11-10 09:02:10 | stdout | [33;1mplexiptv:worker:error [0m    at param (/opt/PlexIPTV/node_modules/express/lib/router/index.js:365:14)
2019-11-10 09:02:10 | stdout | [33;1mplexiptv:worker:error [0m    at Function.process_params (/opt/PlexIPTV/node_modules/express/lib/router/index.js:410:3)
2019-11-10 09:02:10 | stdout | [33;1mplexiptv:worker:error [0m    at next (/opt/PlexIPTV/node_modules/express/lib/router/index.js:275:10)
2019-11-10 09:02:10 | stdout | [33;1mplexiptv:worker:error [0m    at expressInit (/opt/PlexIPTV/node_modules/express/lib/middleware/init.js:40:5)
2019-11-10 09:02:10 | stdout | [33;1mplexiptv:worker:error [0m    at Layer.handle [as handle_request] (/opt/PlexIPTV/node_modules/express/lib/router/layer.js:95:5) ] [33m+2m[0m
2019-11-10 09:02:10 | stdout | [36;1mplexiptv:preloader:verbose [0m2019/11/10 09:02:09.9970 🔭 [32mpreload[39m Create preload for: http://localhost:1245/channel/80019 [36m+1m[0m
2019-11-10 09:02:10 | stdout | [33;1mplexiptv:worker:verbose [0m2019/11/10 09:02:09.9970 🔭 [32msubscribe[39m Subscribe to: http://localhost:1245/channel/80019 [33m+3ms[0m
2019-11-10 09:02:12 | stdout | [33;1mplexiptv:dvr:verbose [0m2019/11/10 09:02:12.9680 🔭 [32mdiscover[39m Received a discover request. [33m+3s[0m
2019-11-10 09:02:12 | stdout | [33;1mplexiptv:dvr:verbose [0m2019/11/10 09:02:12.9750 🔭 [32mlineupStatus[39m Received a lineup status request. [33m+7ms[0m
2019-11-10 09:02:15 | stdout | [33;1mplexiptv:dvr:verbose [0m2019/11/10 09:02:15.9830 🔭 [32mdiscover[39m Received a discover request. [33m+3s[0m
2019-11-10 09:02:15 | stdout | [33;1mplexiptv:dvr:verbose [0m2019/11/10 09:02:15.9900 🔭 [32mlineupStatus[39m Received a lineup status request. [33m+7ms[0m
2019-11-10 09:02:19 | stdout | [33;1mplexiptv:dvr:verbose [0m2019/11/10 09:02:18.9990 🔭 [32mdiscover[39m Received a discover request. [33m+3s[0m
2019-11-10 09:02:19 | stdout | [33;1mplexiptv:dvr:verbose [0m2019/11/10 09:02:19.0070 🔭 [32mlineupStatus[39m Received a lineup status request. [33m+7ms[0m
2019-11-10 09:02:22 | stdout | [33;1mplexiptv:dvr:verbose [0m2019/11/10 09:02:22.0160 🔭 [32mdiscover[39m Received a discover request. [33m+3s[0m
2019-11-10 09:02:22 | stdout | [33;1mplexiptv:dvr:verbose [0m2019/11/10 09:02:22.0230 🔭 [32mlineupStatus[39m Received a lineup status request. [33m+8ms[0m
2019-11-10 09:02:25 | stdout | [33;1mplexiptv:dvr:verbose [0m2019/11/10 09:02:25.0320 🔭 [32mdiscover[39m Received a discover request. [33m+3s[0m
2019-11-10 09:02:25 | stdout | [33;1mplexiptv:dvr:verbose [0m2019/11/10 09:02:25.0390 🔭 [32mlineupStatus[39m Received a lineup status request. [33m+7ms[0m
2019-11-10 09:02:28 | stdout | [33;1mplexiptv:dvr:verbose [0m2019/11/10 09:02:28.0470 🔭 [32mdiscover[39m Received a discover request. [33m+3s[0m
2019-11-10 09:02:28 | stdout | [33;1mplexiptv:dvr:verbose [0m2019/11/10 09:02:28.0550 🔭 [32mlineupStatus[39m Received a lineup status request. [33m+7ms[0m
2019-11-10 09:02:31 | stdout | [33;1mplexiptv:dvr:verbose [0m2019/11/10 09:02:31.0640 🔭 [32mdiscover[39m Received a discover request. [33m+3s[0m
2019-11-10 09:02:31 | stdout | [33;1mplexiptv:dvr:verbose [0m2019/11/10 09:02:31.0720 🔭 [32mlineupStatus[39m Received a lineup status request. [33m+8ms[0m
2019-11-10 09:02:34 | stdout | [33;1mplexiptv:dvr:verbose [0m2019/11/10 09:02:34.0800 🔭 [32mdiscover[39m Received a discover request. [33m+3s[0m
2019-11-10 09:02:34 | stdout | [33;1mplexiptv:dvr:verbose [0m2019/11/10 09:02:34.0870 🔭 [32mlineupStatus[39m Received a lineup status request. [33m+7ms[0m
2019-11-10 09:02:34 | stdout | [33;1mplexiptv:worker:verbose [0m2019/11/10 09:02:34.9720 🔭 [32munsubscribe[39m Unsubscribe to: http://localhost:1245/channel/80019 [33m+25s[0m
2019-11-10 09:02:34 | stdout | [33;1mplexiptv:worker:verbose [0m2019/11/10 09:02:34.9730 🔭 [32munsubscribe[39m No more subscribers. [33m+1ms[0m
2019-11-10 09:02:34 | stdout | [33;1mplexiptv:worker:verbose [0m2019/11/10 09:02:34.9740 🔭 [32mend[39m End of: http://localhost:1245/channel/80019 [33m+1ms[0m
2019-11-10 09:02:34 | stdout | [36;1mplexiptv:preloader:verbose [0m2019/11/10 09:02:34.9750 🔭 [32mremoveWorker[39m Remove preload for: http://localhost:1245/channel/80019 [36m+25s[0m
2019-11-10 09:02:34 | stdout | [33;1mplexiptv:dvr:verbose [0m2019/11/10 09:02:34.9880 🔭 [32mdiscover[39m Received a discover request. [33m+902ms[0m
2019-11-10 09:02:34 | stdout | [33;1mplexiptv:dvr:verbose [0m2019/11/10 09:02:34.9970 🔭 [32mlineupStatus[39m Received a lineup status request. [33m+8ms[0m

```

**Comment by xiaodoudou** [comment]
Took me far too long to actually read your log properly. Here's the culprit:

```
rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=497
```

The Freebox playlist is RTSP, and PlexIPTV only spoke HTTP. So "Invalid protocol" was being completely literal, and it was never a Synology problem at all. Sorry for the runaround.

Anyway: **RTSP channels play as of [1.3.0](https://github.com/xiaodoudou/PlexIPTV/releases/tag/1.3.0).** The stream is handed to ffmpeg, which repackages it as MPEG-TS with `-c copy`, so nothing is re-encoded and the picture is untouched.

Two things you'll need for the Freebox specifically:

1. **ffmpeg has to be installed** and on `PATH` (or set `PLEXIPTV_FFMPEG` to its location). It's only needed for RTSP and one uncommon flavour of HLS, not for normal streams.
2. **`"allowPrivateNetwork": true` in your settings.** `mafreebox.freebox.fr` is your own router, and since 1.1.0 LAN addresses are refused by default so a tampered playlist can't aim the proxy at your internal network. Your case is exactly what the opt-in is for.

One thing I can't promise: Free's TV is multicast in a lot of setups, and I've only been able to test RTSP against unicast sources. If it still doesn't play after those two steps, open a new issue with the log and I'll take a look, that would be a separate problem from this one.

If you're still running this five years on, I'd genuinely like to know whether it works.
